name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release"
        type: string

env:
  MISE_EXPERIMENTAL: 1
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: read
  statuses: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: "macos-latest"
    timeout-minutes: 15
    if: "!startsWith(github.event.head_commit.message, '[Release]')"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: brew install xz
      - name: Check if there are releasable changes
        id: is-releasable
        run: |
          bumped_output=$(git cliff --bump --unreleased)
          changelog_content=$(cat CHANGELOG.md)

          bumped_hash=$(echo -n "$bumped_output" | shasum -a 256 | awk '{print $1}')
          changelog_hash=$(echo -n "$changelog_content" | shasum -a 256 | awk '{print $1}')

          if [ "$bumped_hash" != "$changelog_hash" ]; then
            echo "should-release=true" >> $GITHUB_ENV
          else
            echo "should-release=false" >> $GITHUB_ENV
          fi

      - name: Get next version
        id: next-version
        if: env.should-release == 'true'
        run: echo "NEXT_VERSION=$(git cliff --bumped-version)" >> "$GITHUB_OUTPUT"
      - name: Update CHANGELOG.md
        if: env.should-release == 'true'
        run: git cliff --bump -o CHANGELOG.md
      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        if: env.should-release == 'true'
        with:
          commit_options: "--allow-empty"
          tagging_message: ${{ steps.next-version.outputs.NEXT_VERSION }}
          skip_dirty_check: true
          commit_message: "[Release] sidekick ${{ steps.next-version.outputs.NEXT_VERSION }}"
      - name: Get release notes
        id: release-notes
        if: env.should-release == 'true'
        run: |
          echo "RELEASE_NOTES<<EOF" >> "$GITHUB_OUTPUT"
          git cliff --latest >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - env:
          SIDEKICK_VERSION: ${{ steps.next-version.outputs.NEXT_VERSION }}
        run: mise run release:macos
      - env:
          SIDEKICK_VERSION: ${{ steps.next-version.outputs.NEXT_VERSION }}
        run: mise run release:linux
      - name: Sign macOS binary
        run: |
          TMP_DIR=$(mktemp -d)
          KEYCHAIN_PASSWORD=$(uuidgen)
          KEYCHAIN_PATH=$TMP_DIR/keychain.keychain
          CERTIFICATE_PATH=$TMP_DIR/certificate.p12
          CERTIFICATE_NAME="Developer ID Application: Tuist GmbH (U6LC622NKF)"

          echo "$MACOS_SIGNING_CERTIFICATE_BASE64" | base64 --decode > $CERTIFICATE_PATH
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security import $CERTIFICATE_PATH -P $CERTIFICATE_PASSWORD -A

          /usr/bin/codesign --sign "$CERTIFICATE_NAME" --timestamp --options runtime --verbose burrito_out/sidekick_macos
      - run: |
          mv burrito_out/sidekick_linux burrito_out/sidekick-linux-arm64
          mv burrito_out/sidekick_macos burrito_out/sidekick-macos-arm64
          tar -czvf burrito_out/sidekick-linux-arm64.tar.gz burrito_out/sidekick-linux-arm64
          tar -czvf burrito_out/sidekick-macos-arm64.tar.gz burrito_out/sidekick-macos-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: env.should-release == 'true'
        with:
          draft: false
          repository: tuist/sidekick
          name: ${{ steps.next-version.outputs.NEXT_VERSION }}
          tag_name: ${{ steps.next-version.outputs.NEXT_VERSION }}
          body: ${{ steps.release-notes.outputs.RELEASE_NOTES }}
          target_commitish: ${{ steps.auto-commit-action.outputs.commit_hash }}
          files: |
            burrito_out/sidekick-linux-arm64
            burrito_out/sidekick-linux-arm64.tar.gz
            burrito_out/sidekick-macos-arm64
            burrito_out/sidekick-macos-arm64.tar.gz
      - name: Generate checksums
        uses: thewh1teagle/checksum@v1
        with:
          tag: ${{ steps.next-version.outputs.NEXT_VERSION }}
